// const seedCategoryExams = require('./category_exam')
const seedRoles = require('./role')
const seedUsers = require('./user')
const seedCourses = require('./course')
const seedCategoryLession = require('./category_lession')
const seedEnrollment = require('./enrollment')
const seedCourseProgress = require('./course_progress')
const seedLessions = require('./lession')
const seedExams = require('./exam')
const seedQuestions = require('./question')
const seedExamQuestions = require('./examQuestion')
const seedUserAnswerHistories = require('./userAnswerHistory')
const seedQuestionDiscussions = require('./questionDiscussion')
const seedTempUserAnswers = require('./tempUserAnswer')
const seedUserEnterExitExamRooms = require('./userEnterExitExamRoom')
const seedCategoryCourses = require('./category_course')
const seedNotifications = require('./notification')
const seedNotificationRecipient = require('./notification_recipient')
const seedOrder = require('./order')
const seedOrderItems = require('./orderItem')
const seedPayments = require('./payment')
const seedCourseReviews = require('./course_review')
const seedDatabase = async () => {
  try {
    await seedCategoryCourses()
    // await seedCategoryExams()
    await seedRoles()
    await seedUsers()
    await seedNotifications()
    await seedNotificationRecipient()
    await seedCourses()
    await seedCategoryLession()
    await seedLessions()
    await seedEnrollment()
    await seedCourseProgress()
    await seedExams()
    await seedQuestions()
    await seedExamQuestions()
    await seedUserAnswerHistories()
    await seedQuestionDiscussions()
    await seedTempUserAnswers()
    await seedUserAnswerHistories()
    await seedUserEnterExitExamRooms()
    await seedOrder()
    await seedOrderItems()
    await seedPayments()
    await seedCourseReviews()
  } catch (error) {
    console.log(`Failed to seed database: ${error}`)
  }
}

module.exports = seedDatabase
