// const seedCategoryExams = require('./category_exam')
const seedRoles = require('./role')
const seedUsers = require('./user')
const seedCourses = require('./course')
const seedCategoryLession = require('./category_lession')
const seedOrder = require('./order')
const seedPayments = require('./payment')
const seedEnrollment = require('./enrollment')
const seedCourseProgress = require('./course_progress')
const seedStudyItems = require('./study_item')
const seedLessions = require('./lession')
const seedExams = require('./exam')
const seedQuestions = require('./question')
const seedUserAnswerHistories = require('./userAnswerHistory')
const seedTempUserAnswers = require('./tempUserAnswer')
const seedUserEnterExitExamRooms = require('./userEnterExitExamRoom')
const seedCategoryCourses = require('./category_course')
const seedNotifications = require('./notification')
const seedNotificationRecipient = require('./notification_recipient')
const seedDatabase = async () => {
  try {
    await seedCategoryCourses()
    await seedRoles()
    await seedUsers()
    await seedNotifications()
    await seedNotificationRecipient()
    await seedCourses()
    await seedCategoryLession()
    await seedStudyItems()
    await seedLessions()
    await seedExams()
    await seedOrder()
    await seedPayments()
    await seedEnrollment()
    await seedCourseProgress()
    await seedQuestions()
    await seedUserAnswerHistories()
    await seedTempUserAnswers()
    await seedUserAnswerHistories()
    await seedUserEnterExitExamRooms()
  } catch (error) {
    console.log(`Failed to seed database: ${error}`)
  }
}

module.exports = seedDatabase
