const seedCategoryExams = require('./category_exam')
const seedPermissions = require('./permission')
const seedRoles = require('./role')
const seedRoleToPermissions = require('./role_to_permission')
const seedUsers = require('./user')
const seedCourses = require('./course')
const seedCategoryLession = require('./category_lession')
const seedEnrollment = require('./enrollment')
const seedCourseProgress = require('./course_progress')
const seedLessions = require('./lession')
const seedExams = require('./exam')
const seedQuestions = require('./question')
const seedExamQuestions = require('./examQuestion')
const seedUserAnswerHistories = require('./userAnswerHistory')
const seedQuestionDiscussions = require('./questionDiscussion')
const seedTempUserAnswers = require('./tempUserAnswer')
const seedUserEnterExitExamRooms = require('./userEnterExitExamRoom')
const seedCategoryCourses = require('./category_course')
const seedRoutes = require('./route')
const seedGroups = require('./group')
const seedNotifications = require('./notification')
const seedNotificationRecipient = require('./notification_recipient')
const seedDatabase = async () => {
  try {
    await seedCategoryCourses()
    await seedCategoryExams()
    await seedPermissions()
    await seedRoles()
    await seedGroups()
    await seedUsers()
    await seedNotifications()
    await seedNotificationRecipient()
    await seedRoleToPermissions()
    await seedCourses()
    await seedCategoryLession()
    await seedLessions()
    await seedEnrollment()
    await seedCourseProgress()
    await seedExams()
    await seedQuestions()
    await seedExamQuestions()
    await seedUserAnswerHistories()
    await seedQuestionDiscussions()
    await seedTempUserAnswers()
    await seedUserAnswerHistories()
    await seedUserEnterExitExamRooms()
    await seedRoutes()
  } catch (error) {
    console.log(`Failed to seed database: ${error}`)
  }
}

module.exports = seedDatabase
